import 'package:get/get.dart';

class MyLocal implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>
      {
        "ar":{"1":"تسجيل الدخول",
          "2":"انشاء حساب",
          "3":"اللغة",
          "4":"العربية",
          "5":"الانكليزية",
          "Type":"النوع",
          "Student":"طالب",
          "Teacher":"استاذ",
          "Full name":"الاسم الكامل",
          "Email Adress":"الايميل",
          "Password":"كلمة المرور",
          "confirm your password":"تأكيد كلمة المرور",
          "phone":"الهاتف",
          "12":"الأعدادات",
          "13":"خروج",
          "14":"اكتب الاسم",
          "15":"ادخل الأيميل",
          "16":"اكتب كلمة المرور",
          "17":"ادخل رقم الهاتف",
          "Registe":"انشاء",
          "19":"هل لديك حساب اخر؟",
          "Login":"سجل",
          "21":"المساعدة",
          "Developer":"المطور",
        "Sort":"المحتوى",
        "Math":"رياضيات",
        "Sciences":"علوم",
        "Geography":"جغرافيا",
        "History":"تاريخ",
        "Arabic":"عربي",
        "English":"انكليزي",
        "Franch":"فرنسي",
        "Physics":"فيزياء",
        "Chemistry":"كيمياء",
        "Arts":"رسم",
          "34":"الأصدقاء",
          "35":"نوع البوست",
          "what are thinking":"ماذا تفكر؟",
          "Post":"نشر",
          "38":"الملف الشخصي",
          "39":"تعديل الملف",
          "40":"المتابعون",
          "41":"المتابعة",
          "Edit Profile":"تعديل الملف الشخصي",
          "43":"تغيير الصورة",
          "44":"تغيير اسمك",
          "45":"اختيار اللغة",
          "Edit":"تعديل",
          "Delete":"حذف",
          "Report":"ابلاغ",
          "Link":"الرابط",
          "Coursesss":"الدروس",
          "Theme":"اللون",
          "Search":"البحث",
        },
        "en": {"1": "Log in",
          "2": "Register",
          "3": "language",
          "4": "Arabic",
          "5": "Englash",
          "Type": "Type",
          "Student":"Student",
          "Teacher":"Teacher",
          "Full name": "Full name",
          "Email Adress": "Email Adress",
          "Password": "Password",
          "confirm your password": "confirm your password",
          "phone": "phone",
          "12": "Setting",
          "13": "Logout",
          "14": "Write your name",
          "15": "Enter your email",
          "16": "Write your password",
          "17": "Enter your number",
          "Registe":"Registe",
          "19":"Do you have an account?",
          "Login":"Login",
          "21":"Help",
          "Developer":"Developer",
          "Sort":"Sort",
          "Math":"Math",
          "Sciences":"Sciences",
          "Geography":"Geography",
          "History":"History",
          "Arabic":"Arabic",
          "English":"English",
          "Franch":"Franch",
          "Physics":"Physics",
          "Chemistry":"Chemistry",
          "Arts":"Arts",
          "34":"Friends",
          "35":"type of post",
          "what are thinking":"what are thinking",
          "Post":"Post",
          "38":"Profile",
          "Edit Profile":"Edit Profile",
          "40":"Followers",
          "41":"Following",
          "42":"Edit Profile",
          "43":"Change Photo",
          "44":"Change your name",
          "45":"Choose language",
          "Edit":"Edit",
          "Delete":"Delete",
          "Report":"Report",
          "Link":"Link",
          "Coursess":"Coursess",
          "Theme":"Theme",
          "Search":"Search",
        }
      };


}